message("C compiler: " ${CMAKE_C_COMPILER})
message("C compiler version: " ${CMAKE_C_COMPILER_VERSION})
message("")
message("C++ compiler: " ${CMAKE_CXX_COMPILER})
message("C++ compiler version: " ${CMAKE_CXX_COMPILER_VERSION})
message("")
message("Compile mode: " ${CMAKE_BUILD_TYPE})
message("C standard: " ${CMAKE_C_STANDARD})
message("C++ standard: " ${CMAKE_CXX_STANDARD})
message("")