add_compile_definitions(CONSOLE)

if(MSVC)
    add_compile_options(/utf-8)
    add_link_options(/MACHINE:X64)
    add_compile_definitions(SANDTABLE_PLATFORM_WINDOWS)
    if(CMAKE_BUILD_TYPE MATCHES "DEBUG")
        add_compile_definitions(SANDTABLE_DEBUG)
    endif()
    if (CMAKE_BUILD_TYPE MATCHES "Release")
        add_compile_definitions(SANDTABLE_RELEASE)
    endif()
endif ()